version: 2.0

config_android: &config_android
  docker:
    - image: circleci/android:api-28-alpha
  working_directory: ~/dank
  environment:
    JAVA_TOOL_OPTIONS: "-Xmx1024m"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
    TERM: dumb

update_sdk: &update_sdk
  run:
    name: Update SDK
    command: |
      mkdir "$ANDROID_HOME/licenses" || true
      echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
      echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
      sdkmanager "platform-tools" "platforms;android-28"

save_cache: &save_cache
  save_cache:
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper
    key: gradle-{{ checksum "app/build.gradle" }}-{{ checksum "markdownhints/build.gradle" }}

restore_cache: &restore_cache
  restore_cache:
    key: gradle-{{ checksum "app/build.gradle" }}-{{ checksum "markdownhints/build.gradle" }}

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/dank

persist_workspace: &persist_workspace
  persist_to_workspace:
    root: .
    paths:
      - ./*/build

workflow_filter_all: &workflow_filter_all
  filters:
    tags:
      only: /.*/

setup_signing: &setup_signing
  run:
    name: Setting-up signing configuration
    command: signing/setup.sh $ENCRYPT_KEY
cleanup_signing: &cleanup_signing
  run:
    name: Cleaning-up signing configuration
    command: signing/cleanup.sh

jobs:
  build_debug:
    <<: *config_android
    steps:
      - <<: *update_sdk
      - checkout
      - <<: *restore_cache
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - <<: *save_cache
      - run:
          name: Assemble debug APKs
          command: ./gradlew :app:bundleDebug :app:assembleDebug
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - <<: *persist_workspace

  build_release:
    <<: *config_android
    steps:
      - <<: *update_sdk
      - checkout
      - <<: *restore_cache
      - <<: *setup_signing
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - <<: *save_cache
      - run:
          name: Assemble release APKs
          command: ./gradlew :app:bundleRelease :app:assembleRelease
      - <<: *cleanup_signing
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - <<: *persist_workspace

  check:
    <<: *config_android
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_cache
      - run:
          name: Check app
          command: ./gradlew check
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  publish_github_release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - <<: *attach_workspace
      - run:
          name: Publish Release on GitHub
          command: |
            go get github.com/tcnksm/ghr
            RELEASE_APK="Dank_${CIRCLE_TAG}.apk"
            mv ~/dank/app/build/outputs/apk/release/app-release.apk ${RELEASE_APK}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ${RELEASE_APK}

workflows:
  version: 2
  build_test_publish:
    jobs:
      - build_debug:
          <<: *workflow_filter_all
#      - check:
#          requires:
#            - build_debug
      - build_release:
          filters:
            tags:
              only: /^\d+\.\d+(\.\d+)?$/
            branches:
              ignore: /.*/
      - publish_github_release:
          requires:
            - build_release
          filters:
            tags:
              only: /^\d+\.\d+(\.\d+)?$/
            branches:
              ignore: /.*/
