name: Release
on:
  push:
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Preparation

      - name: Checkout
        uses: actions/checkout@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      # Cache

      - name: Generate cache key
        run: ./checksum.sh checksum.txt

      - name: Cache gradle modules
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/modules-2
          key: ${{ runner.os }}-gradlemodules-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-gradlemodules-

      - name: Cache gradle jars
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/jars-3
          key: ${{ runner.os }}-gradlejars-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-gradlejars-

      - name: Cache gradle build
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/build-cache-1
          key: ${{ runner.os }}-gradlebuildcache-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-gradlebuildcache-

      # Signing

      - name: Setup signing
        env:
          SIGNING_ENCRYPTION_KEY: ${{ secrets.SIGNING_ENCRYPTION_KEY }}
        run: ./signing/setup.sh "$SIGNING_ENCRYPTION_KEY"

      # Release APK

      - name: Assemble release APK
        run: ./gradlew :app:bundleRelease :app:assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@master
        with:
          name: Dawn Release APK
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload release Bundle
        uses: actions/upload-artifact@master
        with:
          name: Dawn Release Bundle
          path: app/build/outputs/bundle/release/app-release.aab

      # Cleanup

      - name: Cleanup signing
        if: always()
        run: ./signing/cleanup.sh
